function [] = latex_figure(fig, figname, fileID)

    longname = figname;
    figname(figname == ' ') = '_';
    export_fig(fig, ['./opt_report/',figname], '-jpg', '-r100' );
    fprintf(fileID, ...
    ['\\begin{figure}[H]\n', ...
    '\\includegraphics[width=\\linewidth]{',figname,'.jpg}\n', ...
    '\\caption{', longname,'}\n', ...
    '\\label{fig:', figname, '}\n', ...
    '\\end{figure}\n\n']);
end