function [] = plot_ed_output(data,c13,years,save)
% COMPARE_MPOST_DATA Takes as input data supplied in mpost's output format
% and outputs graphs of that data.
%----------------------------------------------------------------------
%  Input: data - the data substructure of an mpost file.
%          c13 - Graph C13; T,F = 1,0
%         type - 'many' or 'few', defines which graphs to produce.
%        years - [first year, last year] to graph
%
% Example: gen_many_graphs_v3(mpost.data,1,'few',[2009,20010],0)
%----------------------------------------------------------------------

%save = 0;

%% Set up vars passed to plot utilitis
%--------- Var name --------------- Description ----------- Location --- Units ------ Fig #
items = { 'MMEAN_BLEAF_CO'         'Leaf Biomass'          'T'          'kgC/m^2'      1;...
          'MMEAN_BSTORAGE_CO'      'Storage Biomass'       'T'          'kgC/m^2'      1;...
          'MMEAN_BROOT_CO'         'Root Biomass'          'T'          'kgC/m^2'      1;...
          'AGB_CO'                 'Above Ground Biomass'  'T'          'kgC/m^2'      1;...
          'MMEAN_FAST_SOIL_C'      'Mean Fast Soil C'      'T'          'kgC/m^2'      1;...
          'MMEAN_SLOW_SOIL_C'      'Mean Slow Soil C'      'T'          'kgC/m^2'      1;...
          ...
          'MMEAN_LEAF_RESP_CO'     'Mean Leaf Resp'        'T'          'kgC/m^2/yr'   2;...
          'MMEAN_ROOT_RESP_CO'     'Mean Root Resp'        'T'          'kgC/m^2/yr'   2;...
          'MMEAN_VLEAF_RESP_CO'    'Mean VLeaf Resp'       'T'          'kgC/m^2/yr'   2;...
          'MMEAN_STORAGE_RESP_CO'  'Mean Storage Resp'     'T'          'kgC/m^2/yr'   2;...
          'MMEAN_GROWTH_RESP_CO'   'Mean Growth Resp'      'T'          'kgC/m^2'      2;...
          'MMEAN_PLRESP_CO'        'Mean Plant Resp'       'T'          '%'            2;...
          ...
          'MMEAN_GPP_CO'           'Mean GPP'              'T'          'kgC/m^2/yr'   3;...
          'MMEAN_NPP_CO'           'Mean NPP'              'T'          'kgC/m^2/yr'   3;...
          'MMEAN_PLRESP_CO'        'Mean Plant Resp'       'T'          'kgC/m^2/yr'   3;...
          'MMEAN_RH_PY'            'Mean Het. Resp.'       'T'          'kgC/m^2/yr'   3;...
          ...
          'CB'                     'Carbon Balance'        'T'          'kgC/m^2'      4;
          ...
          'BA_CO'                  'Total Basal Area'      'T'          'm'            5;...
          'HITE'                   'Plant Heights'         'T'          'm'            5;...
          'MMEAN_MORT_RATE_CO'     'Mortality by Type'     'T'          '1/yr'         5;
          ...
          'Het_SResp_Frac'         'Het Soil Resp Frac'    'T'          'kgC/m^2'      6;...
          'Total_Bgrnd_Flux'       'Flux Below Ground'     'H'          'kgC/m^2/yr'   6;...
          'Frac_Bgrnd_Flux'        'Frac Blgrnd Flux'      'H'          '%'            6;...
         };

fignames = {'Biomass', 'Plant Resp', 'Some Fluxes', 'Belowground Items'};
fnums = cell2mat(items(:,5));
   
%% Plot things. %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%:
for ifig = 1:4  %range(fnums)
   %killpanel = -1;
   names = items(fnums == ifig,1);
   alias = items(fnums == ifig,2);
   prfix = items(fnums == ifig,3);
   units = items(fnums == ifig,4);
   
   if c13 == 0 || c13 == 1
      util_panel_plot(fignames{ifig}, ...
                data,...
                names,...
                alias,...
                units,...
                prfix,...
                years,...
                save);
   end
   if c13 == 1 || c13 == 2
      if ifig >= 4;
          continue;
      end
      
      fignames{ifig} = [fignames{ifig} ' delta 13C'];
      for i = 1:numel(names)
          names{i}  = [names{i} '_d13C'];
          alias{i}  = [alias{i} ' \delta ^1^3C'];
          units{i}  = 'permil';
      end
      if ifig == 1 
          killpanel = 4;
      end
      util_panel_plot(fignames{ifig}, ...
                data,...
                names,...
                alias,...
                units,...
                prfix,...
                years,...
                save,...
                killpanel);
   end
end

end
