function [] = plot_general(data,plot_c13,splt,save)
% COMPARE_MPOST_DATA Takes as input data supplied in mpost's output format
% and outputs graphs of that data.
%----------------------------------------------------------------------
%  Input: data - the data substructure of an mpost file.
%          c13 - Graph C13; T,F = 1,0
%         type - 'many' or 'few', defines which graphs to produce.
%        years - [first year, last year] to graphclear
%
% Example: gen_many_graphs_v3(mpost.data,1,'few',[2009,20010],0)
%----------------------------------------------------------------------
years    = [];

%% Set up vars passed to plot utilitis
%--------- Var name --------------- Description ----------- Location --- Units ------ Fig - Splt
items = { 'MMEAN_BLEAF_CO'             'Leaf Biomass'          'T'      'kgC/m^2'      1   1;...
          'MMEAN_BROOT_CO'             'Root Biomass'          'T'      'kgC/m^2'      1   1;...
          'MMEAN_LAI_CO'               'Leaf Area Index'       'T'      'm^2l/m^2g'    1   1;...
          'MMEAN_LEAF_MAINTENANCE_CO'  'Leaf Maintenance Loss' 'T'      'kgC/m^2'      1   1;...
          'MMEAN_ROOT_MAINTENANCE_CO'  'Root Maintenance Loss' 'T'      'kgC/m^2'      1   1;...
          'MMEAN_LEAF_DROP_CO'         'Dropped Leaf Mass'     'T'      'kgC/m^2'      1   1;...
          'MMEAN_BSTORAGE_CO'          'Storage Biomass'       'T'      'kgC/m^2'      1   1;...
          'CB'                         'Carbon Balance'        'T'      'kgC/m^2'      1   1;...
          'BA_CO'                      'Total Basal Area'      'T'      'cm^2/m^2'     1   1;...
          ...
          'MMEAN_LEAF_RESP_CO'         'Mean Leaf Resp'        'T'      'kgC/m^2/yr'   2   1;...
          'MMEAN_ROOT_RESP_CO'         'Mean Root Resp'        'T'      'kgC/m^2/yr'   2   1;...
          'MMEAN_STORAGE_RESP_CO'      'Mean Storage Resp'     'T'      'kgC/m^2/yr'   2   1;...
          'MMEAN_LEAF_GROWTH_RESP_CO'  'Mean Leaf Growth Resp' 'T'      'kgC/m^2/yr'   2   1;...
          'MMEAN_ROOT_GROWTH_RESP_CO'  'Mean Root Growth Resp' 'T'      'kgC/m^2/yr'   2   1;...
          'MMEAN_SAPA_GROWTH_RESP_CO'  'Mean Sapa Growth Resp' 'T'      'kgC/m^2/yr'   2   1;...
          'MMEAN_SAPB_GROWTH_RESP_CO'  'Mean Sapb Growth Resp' 'T'      'kgC/m^2/yr'   2   1;...
          'MMEAN_GPP_CO'               'Mean GPP'              'T'      'kgC/m^2/yr'   2   1;...
          'MMEAN_NPP_CO'               'Mean NPP'              'T'      'kgC/m^2/yr'   2   1;...
          ...
          'MMEAN_FAST_SOIL_C'          'Mean Fast Soil C'      'T'      'kgC/m^2'      3   0;...
          'MMEAN_SLOW_SOIL_C'          'Mean Slow Soil C'      'T'      'kgC/m^2'      3   0;...
          'MMEAN_RH_PA'                'Mean Het. Resp.'       'T'      'kgC/m^2/yr'   3   0;...
          'MMEAN_Soil_Resp'            'Mean Soil Resp.'       'X'      'kgC/m^2/yr'   3   0;...
          'MMEAN_Soil_Resp_HF'         'R_H / R_s_o_i_l'       'X'      'kgC/m^2/yr'   3   0;...
          'MMEAN_Reco_HF'              'R_H / R_e_c_o'         'X'      'kgC/m^2/yr'   3   0;...
          'MMEAN_FAST_SOIL_N'          'Mean Fast Soil N'      'T'      ''             3   0;...
          'MMEAN_MINERAL_SOIL_N_PY'    'Mean Mineral Soil N'   'T'      ''             3   0;...
          'MMEAN_FSN_CO'               'Mean FSN Co'           'T'      ''             3   0;...
          ...
          'MMEAN_LEAF_STORAGE_RESP_CO' 'Mean Leaf Storage Resp' 'T'     'kgC/m^2/yr'   4   1;...
          'MMEAN_ROOT_STORAGE_RESP_CO' 'Mean Root Storage Resp' 'T'     'kgC/m^2/yr'   4   1;...
          'MMEAN_SAPA_STORAGE_RESP_CO' 'Mean Sapa Storage Resp' 'T'     'kgC/m^2/yr'   4   1;...
          'MMEAN_SAPB_STORAGE_RESP_CO' 'Mean Sapb Storage Resp' 'T'     'kgC/m^2/yr'   4   1;...
          ...
          'FMEAN_CARBON_ST_PA'         'Mean Carbon Storage'    'T'     'kgC/m^2/yr'   5   0;...
          'FMEAN_CARBON_AC_PA'         'Mean Atm to CAS C Flux' 'T'     'kgC/m^2/yr'   5   0;...
          'FMEAN_CSTAR_PA'             'Mean C*'                'T'     'kgC/m^2/yr'   5   0;...
          'HITE'                       'Plant Heights'          'T'      'm'           5   0;...
          ...
          'MMEAN_NPPDAILY_CO'          'Mean Daily NPP'            'T'  'kgC/m^2/yr'   6   1;...
          'MMEAN_NPPCROOT_CO'          'Mean Daily NPP to CRoots'  'T'  'kgC/m^2/yr'   6   1;...
          'MMEAN_NPPFROOT_CO'          'Mean Daily NPP to FRoots'  'T'  'kgC/m^2/yr'   6   1;...
          'MMEAN_NPPLEAF_CO'           'Mean Daily NPP to Leaves'  'T'  'kgC/m^2/yr'   6   1;...
          'MMEAN_NPPSAPWOOD_CO'        'Mean Daily NPP to Sapwood' 'T'  'kgC/m^2/yr'   6   1;...
          'MMEAN_NPPSEEDS_CO'          'Mean Daily NPP to Seeds'   'T'  'kgC/m^2/yr'   6   1;...
          'MMEAN_NPPWOOD_CO'           'Mean Daily NPP to Wood'    'T'  'kgC/m^2/yr'   6   1;...
          'MMEAN_NEP_PY'               'Mean NEP'                  'T'  'kgC/m^2/yr'   6   1;...
          'MMEAN_NPP_CO'               'Mean NPP'                  'T'  'kgC/m^2/yr'   6   1;...
          ...
          'Het_SResp_Frac'         'Het Soil Resp Frac'    'T'          'kgC/m^2'      -1   0;...
          'Total_Bgrnd_Flux'       'Flux Below Ground'     'T'          'kgC/m^2/yr'   -1   0;...
          'Frac_Bgrnd_Flux'        'Frac Blgrnd Flux'      'T'          '%'            -1   0;...
         };

fignames = {'Pools', 'Fluxes', 'Belowground Items', 'Storage Flux', 'Canopy Variables & Height' , 'NPP Allocation'};
hw_fname = strcat(fignames,'-Hw');
co_fname = strcat(fignames,'-Co');
fnums = cell2mat(items(:,5));
   
%% Plot things. %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%:
for ifig = 1:6  %range(fnums)
   %killpanel = -1;
   names = items(fnums == ifig,1);
   alias = items(fnums == ifig,2);
   prfix = items(fnums == ifig,3);
   units = items(fnums == ifig,4);
   split = items(fnums == ifig,6);
   %--------------------------------------------------------------------------------------------
   % Total Carbon, Aggregated
   %--------------------------------------------------------------------------------------------
   if splt == 0
      util_panel_plot(fignames{ifig},data,names,alias,units,prfix,years,save);
   end
   %--------------------------------------------------------------------------------------------
   % Total Carbon, PFT-Split
   %--------------------------------------------------------------------------------------------
   if splt > 0

      killpanel = [];
      for i = 1:numel(names)
         prfix{i} = 'H';
         if split{i} == 0;
            killpanel = [killpanel i];
         end
      end
      util_panel_plot(hw_fname{ifig},data,names,alias,units,prfix,years,save,killpanel);
      
      killpanel = [];
      for i = 1:numel(names)
         prfix{i} = 'C';
         if split{i} == 0;
            killpanel = [killpanel i];
         end
      end
      util_panel_plot(co_fname{ifig},data,names,alias,units,prfix,years,save,killpanel);

   end
   
   
   if plot_c13
      if ifig >= 4;
          continue;
      end
      
      fignames{ifig} = [fignames{ifig} ' delta 13C'];
      for i = 1:numel(names)
          [~, names{i}]  = get_iso_name(names{i});
          alias{i}  = [alias{i} ' \delta ^1^3C'];
          units{i}  = 'permil';
      end
      if ifig == 1 
         killpanel = 4:6;
      else
         killpanel = 0;
      end
      util_panel_plot(fignames{ifig}, ...
                data,...
                names,...
                alias,...
                units,...
                prfix,...
                years,...
                save,...
                killpanel);
   end
end

end
