function [] = plot_general(data,resin,plot_c13,splt,save,varargin)
% COMPARE_MPOST_DATA Takes as input data supplied in mpost's output format
% and outputs graphs of that data.
%----------------------------------------------------------------------
%  Input: data - the data substructure of an mpost file.
%        resin - Resolution input, a string of ED resolution codes
%     plot_c13 - Boolean, whould d13C be plotted?
%         splt - String for which pft-type-split vars to show
%         save - Should the plots be saved to disk?
%
% Example: gen_many_graphs_v3(mpost,'DMTY',0,'THC',0)
%----------------------------------------------------------------------
years      = [];
res.fast   = any('F' == resin);
res.daily  = any('D' == resin);
res.month  = any('M' == resin);
res.yearly = any('Y' == resin);
res.tower  = any('T' == resin);

dev = 1;

%% Set up vars passed to plot utilitis
items = {};
fignames = {};
if 0;
   %--------- Var name --------------- Description ----------- Location --- Units ---------- Splt
   fignames{end+1} = 'Inst-Bio';
   items{end+1} = { ... FMEANS:
             'BLEAF_CO'                   'FMean Leaf Biomass'          'T' 'kgC/m^2'         1;...
             'BROOT_CO'                   'FMean Root Biomass'          'T' 'kgC/m^2'         1;...
             'BSAPWOODA_CO'               'FMean Leaf Area Index'       'T' 'm^2/m^2'         1;...
             'BSAPWOODB_CO'               'FMean Dropped Leaf Mass'     'T' 'kgC/m^2'         1;...
             'LEAF_MAINTENANCE_CO'        'FMean Leaf Maintenance Loss' 'T' 'kgC/m^2'         1;...
             'ROOT_MAINTENANCE_CO'        'FMean Root Maintenance Loss' 'T' 'kgC/m^2'         1;...
             'BSTORAGE_CO'                'FMean Storage Biomass'       'T' 'kgC/m^2'         1;...
             'CB'                         'FMean Carbon Balance'        'T' 'kgC/m^2'         1;...
             'LAI_CO'                     'FMean LAI'                   'T' 'cm^2/m^2'        1;...
             };
end
if res.fast
   fignames{end+1} = 'Fast-Bio';
   items{end+1} = { ... FMEANS:
             'FMEAN_BLEAF_CO'             'FMean Leaf Biomass'          'T' 'kgC/m^2'         1;...
             'FMEAN_BROOT_CO'             'FMean Root Biomass'          'T' 'kgC/m^2'         1;...
             'FMEAN_BSAPWOODA_CO'         'FMean SapA Biomass'          'T' 'm^2/m^2'         1;...
             'FMEAN_BSAPWOODB_CO'         'FMean SapB Biomass'          'T' 'kgC/m^2'         1;...
             'FMEAN_LEAF_MAINTENANCE_CO'  'FMean Leaf Maintenance Loss' 'T' 'kgC/m^2'         1;...
             'FMEAN_ROOT_MAINTENANCE_CO'  'FMean Root Maintenance Loss' 'T' 'kgC/m^2'         1;...
             'FMEAN_BSTORAGE_CO'          'FMean Storage Biomass'       'T' 'kgC/m^2'         1;...
             'FMEAN_LEAF_DROP_CO'         'FMean Leaf Drop'             'T' 'kgC/m^2'         1;...
             'FMEAN_LAI_CO'               'FMean LAI'                   'T' 'cm^2/m^2'        1;...
             };

   fignames{end+1} = 'Fast-Fluxes';
   items{end+1} = { ... FMEANS:
          'FMEAN_LEAF_RESP_PY'         'FMean Leaf Resp'        'T'      'kgC/m^2/yr'      1;...
          'FMEAN_ROOT_RESP_PY'         'FMean Root Resp'        'T'      'kgC/m^2/yr'      1;...
          'FMEAN_GPP_CO'               'FMean GPP'              'T'      'kgC/m^2/yr'      1;...
          'FMEAN_NPP_PY'               'FMean NPP'              'T'      'kgC/m^2/yr'      1;...
          };

   fignames{end+1} = 'Fast-SGR';
   items{end+1} = { ... FMEANS:
          'FMEAN_LEAF_STORAGE_RESP_PY' 'FMean Leaf Storage Resp' 'T'     'kgC/m^2/yr'      1;...
          'FMEAN_ROOT_STORAGE_RESP_PY' 'FMean Root Storage Resp' 'T'     'kgC/m^2/yr'      1;...
          'FMEAN_SAPA_STORAGE_RESP_PY' 'FMean Sapa Storage Resp' 'T'     'kgC/m^2/yr'      1;...
          'FMEAN_SAPB_STORAGE_RESP_PY' 'FMean Sapb Storage Resp' 'T'     'kgC/m^2/yr'      1;...
          'FMEAN_LEAF_GROWTH_RESP_PY'  'FMean Leaf Growth Resp'  'T'     'kgC/m^2/yr'      1;...
          'FMEAN_ROOT_GROWTH_RESP_PY'  'FMean Root Growth Resp'  'T'     'kgC/m^2/yr'      1;...
          'FMEAN_SAPA_GROWTH_RESP_PY'  'FMean Sapa Growth Resp'  'T'     'kgC/m^2/yr'      1;...
          'FMEAN_SAPB_GROWTH_RESP_PY'  'FMean Sapb Growth Resp'  'T'     'kgC/m^2/yr'      1;...
          };
end

if res.daily
   fignames{end+1} = 'Daily-Bio';
   items{end+1} = { ... FMEANS:
          'DMEAN_BLEAF_CO'             'DMean Leaf Biomass'          'T' 'kgC/m^2'         1;...
          'DMEAN_BROOT_CO'             'DMean Root Biomass'          'T' 'kgC/m^2'         1;...
          'DMEAN_BSAPWOODA_CO'         'DMean SapwoodA Biomass'      'T' 'm^2/m^2'         1;...
          'DMEAN_BSAPWOODB_CO'         'DMean SapwoodB Biomass'      'T' 'kgC/m^2'         1;...
          'DMEAN_LEAF_MAINTENANCE_CO'  'DMean Leaf Maintenance Loss' 'T' 'kgC/m^2'         1;...
          'DMEAN_ROOT_MAINTENANCE_CO'  'DMean Root Maintenance Loss' 'T' 'kgC/m^2'         1;...
          'DMEAN_BSTORAGE_CO'          'DMean Storage Biomass'       'T' 'kgC/m^2'         1;...
          'DMEAN_CB'                   'DMean Carbon Balance'        'T' 'kgC/m^2'         1;...
          'DMEAN_LAI_CO'               'DMean Leaf Area Index'       'T' 'cm^2/m^2'        1;...
          };
       
   fignames{end+1} = 'Daily-Fluxes';
   items{end+1} = { ... FMEANS:
          'DMEAN_LEAF_RESP_CO'         'DMean Leaf Resp'        'T'      'kgC/m^2/yr'      1;...
          'DMEAN_ROOT_RESP_CO'         'DMean Root Resp'        'T'      'kgC/m^2/yr'      1;...
          'DMEAN_GPP_CO'               'DMean GPP'              'T'      'kgC/m^2/yr'      1;...
          'DMEAN_NPP_CO'               'DMean NPP'              'T'      'kgC/m^2/yr'      1;...
          };
       
   fignames{end+1} = 'Daily-SGR';
   items{end+1} = { ... FMEANS:
          'DMEAN_LEAF_STORAGE_RESP_CO' 'DMean Leaf Storage Resp' 'T'     'kgC/m^2/yr'     1;...
          'DMEAN_ROOT_STORAGE_RESP_CO' 'DMean Root Storage Resp' 'T'     'kgC/m^2/yr'     1;...
          'DMEAN_SAPA_STORAGE_RESP_CO' 'DMean Sapa Storage Resp' 'T'     'kgC/m^2/yr'     1;...
          'DMEAN_SAPB_STORAGE_RESP_CO' 'DMean Sapb Storage Resp' 'T'     'kgC/m^2/yr'     1;...
          'DMEAN_LEAF_GROWTH_RESP_CO'  'DMean Leaf Growth Resp'  'T'     'kgC/m^2/yr'     1;...
          'DMEAN_ROOT_GROWTH_RESP_CO'  'DMean Root Growth Resp'  'T'     'kgC/m^2/yr'     1;...
          'DMEAN_SAPA_GROWTH_RESP_CO'  'DMean Sapa Growth Resp'  'T'     'kgC/m^2/yr'     1;...
          'DMEAN_SAPB_GROWTH_RESP_CO'  'DMean Sapb Growth Resp'  'T'     'kgC/m^2/yr'     1;...
          };

   fignames{end+1} = 'Daily-Soil';
   items{end+1} = { ... FMEANS:
          'DMEAN_FAST_SOIL_C'          'DMean Fast Soil C'      'T'      'kgC/m^2'        0;...
          'DMEAN_SLOW_SOIL_C'          'DMean Slow Soil C'      'T'      'kgC/m^2'        0;...
          'DMEAN_RH_PA'                'DMean Het. Resp.'       'T'      'kgC/m^2/yr'     0;...
          'DMEAN_Soil_Resp'            'DMean Soil Resp.'       'X'      'kgC/m^2/yr'     0;...
          'DMEAN_Soil_Resp_HF'         'DMean R_H / R_s_o_i_l'  'X'      'kgC/m^2/yr'     0;...
          'DMEAN_Reco_HF'              'DMean R_H / R_e_c_o'    'X'      'kgC/m^2/yr'     0;...
          'DMEAN_Reco_HF'              'DMean R_H / R_e_c_o'    'X'      'kgC/m^2/yr'     0;...
          'DMEAN_FAST_SOIL_N'          'DMean Fast Soil N'      'T'      ''               0;...
          'DMEAN_MINERAL_SOIL_N_PY'    'DMean Mineral Soil N'   'T'      ''               0;...
          %'DMEAN_FSN_CO'               'DMean FSN Co'           'T'      ''               0;...
          };
end

if res.month
   fignames{end+1} = 'Month-Bio';
   items{end+1} = { ... FMEANS:
          'MMEAN_BLEAF_CO'             'MMean Leaf Biomass'          'T'      'kgC/m^2'         1;...
          'MMEAN_BROOT_CO'             'MMean Root Biomass'          'T'      'kgC/m^2'         1;...
          'MMEAN_LAI_CO'               'MMean Leaf Area Index'       'T'      'm^2/m^2'         1;...
          'MMEAN_LEAF_MAINTENANCE_CO'  'MMean Leaf Maintenance Loss' 'T'      'kgC/m^2'         1;...
          'MMEAN_ROOT_MAINTENANCE_CO'  'MMean Root Maintenance Loss' 'T'      'kgC/m^2'         1;...
          'MMEAN_LEAF_DROP_CO'         'MMean Dropped Leaf Mass'     'T'      'kgC/m^2'         1;...
          'MMEAN_BSTORAGE_CO'          'MMean Storage Biomass'       'T'      'kgC/m^2'        1;...
          'CB'                         'MMean Carbon Balance'        'T'      'kgC/m^2'        1;...
          'BA_CO'                      'Total Basal Area'            'T'      'cm^2/m^2'       1;...
          };
       
   fignames{end+1} = 'Month-Fluxes';
   items{end+1} = { ... FMEANS:
          'MMEAN_LEAF_RESP_CO'         'MMean Leaf Resp'        'T'      'kgC/m^2/yr'     1;...
          'MMEAN_ROOT_RESP_CO'         'MMean Root Resp'        'T'      'kgC/m^2/yr'     1;...
          'MMEAN_GPP_CO'               'MMean GPP'              'T'      'kgC/m^2/yr'     1;...
          'MMEAN_NPP_CO'               'MMean NPP'              'T'      'kgC/m^2/yr'     1;...
          };

   fignames{end+1} = 'Month-SGR';
   items{end+1} = { ... FMEANS:
          'MMEAN_LEAF_STORAGE_RESP_CO' 'MMean Leaf Storage Resp' 'T'     'kgC/m^2/yr'     1;...
          'MMEAN_ROOT_STORAGE_RESP_CO' 'MMean Root Storage Resp' 'T'     'kgC/m^2/yr'     1;...
          'MMEAN_SAPA_STORAGE_RESP_CO' 'MMean Sapa Storage Resp' 'T'     'kgC/m^2/yr'     1;...
          'MMEAN_SAPB_STORAGE_RESP_CO' 'MMean Sapb Storage Resp' 'T'     'kgC/m^2/yr'     1;...
          'MMEAN_LEAF_GROWTH_RESP_CO'  'MMean Leaf Growth Resp'  'T'     'kgC/m^2/yr'     1;...
          'MMEAN_ROOT_GROWTH_RESP_CO'  'MMean Root Growth Resp'  'T'     'kgC/m^2/yr'     1;...
          'MMEAN_SAPA_GROWTH_RESP_CO'  'MMean Sapa Growth Resp'  'T'     'kgC/m^2/yr'     1;...
          'MMEAN_SAPB_GROWTH_RESP_CO'  'MMean Sapb Growth Resp'  'T'     'kgC/m^2/yr'     1;...
          };
       
   fignames{end+1} = 'Month-Soil';
   items{end+1} = { ... FMEANS:
          'MMEAN_FAST_SOIL_C'          'MMean Fast Soil C'      'T'      'kgC/m^2'        0;...
          'MMEAN_SLOW_SOIL_C'          'MMean Slow Soil C'      'T'      'kgC/m^2'        0;...
          'MMEAN_RH_PA'                'MMean Het. Resp.'       'T'      'kgC/m^2/yr'     0;...
          'MMEAN_Soil_Resp'            'MMean Soil Resp.'       'X'      'kgC/m^2/yr'     0;...
          'MMEAN_Soil_Resp_HF'         'MMean R_H / R_s_o_i_l'  'X'      'kgC/m^2/yr'     0;...
          'MMEAN_Reco_HF'              'MMean R_H / R_e_c_o'    'X'      'kgC/m^2/yr'     0;...
          'MMEAN_FAST_SOIL_N'          'MMean Fast Soil N'      'T'      ''               0;...
          'MMEAN_MINERAL_SOIL_N_PY'    'MMean Mineral Soil N'   'T'      ''               0;...
          'MMEAN_FSN_CO'               'MMean FSN Co'           'T'      ''               0;...
          };

   fignames{end+1} = 'Month-NPP-Alloc';
   items{end+1} = { ... FMEANS:
          'MMEAN_NPPDAILY_CO'          'MMean Daily NPP'            'T'  'kgC/m^2/yr'   1;...
          'MMEAN_NPPCROOT_CO'          'MMean Daily NPP to CRoots'  'T'  'kgC/m^2/yr'   1;...
          'MMEAN_NPPFROOT_CO'          'MMean Daily NPP to FRoots'  'T'  'kgC/m^2/yr'   1;...
          'MMEAN_NPPLEAF_CO'           'MMean Daily NPP to Leaves'  'T'  'kgC/m^2/yr'   1;...
          'MMEAN_NPPSAPWOOD_CO'        'MMean Daily NPP to Sapwood' 'T'  'kgC/m^2/yr'   1;...
          'MMEAN_NPPSEEDS_CO'          'MMean Daily NPP to Seeds'   'T'  'kgC/m^2/yr'   1;...
          'MMEAN_NPPWOOD_CO'           'MMean Daily NPP to Wood'    'T'  'kgC/m^2/yr'   1;...
          'MMEAN_NEP_PY'               'MMean NEP'                  'T'  'kgC/m^2/yr'   1;...
          'MMEAN_NPP_CO'               'MMean NPP'                  'T'  'kgC/m^2/yr'   1;...
          };
end

if res.yearly
   fignames{end+1} = 'Yearly-Bio';
   items{end+1} = { ... FMEANS:
          'BAG'                        'YMean Basal Area Growth'   'T'  'm^2/ha/yr'    1;...
          'BAM'                        'YMean Basal Area Mort  '   'T'  'm^2/ha/yr'    1;...
   };
end
...          'FMEAN_CARBON_ST_PA'         'Mean Carbon Storage'    'T'     'kgC/m^2/yr'   8   0;...
...          'FMEAN_CARBON_AC_PA'         'Mean Atm to CAS C Flux' 'T'     'kgC/m^2/yr'   8   0;...
...          'FMEAN_CSTAR_PA'             'Mean C*'                'T'     'kgC/m^2/yr'   8   0;...
...          'HITE'                       'Plant Heights'          'T'      'm'           8   0;...

hw_fname = strcat(fignames,'-Hw');
co_fname = strcat(fignames,'-Co');
nfigs    = length(items); % Not "Actual" number of figs necessarily, just the "base" number

% Plot things
for ifig = 1:nfigs
   names = items{ifig}(:,1);
   alias = items{ifig}(:,2);
   prfix = items{ifig}(:,3);
   units = items{ifig}(:,4);
   split = items{ifig}(:,5);
   
   %--------------------------------------------------------------------------------------------
   % Total Carbon, Aggregated
   %--------------------------------------------------------------------------------------------
   if any(splt == 'T');
      util_panel_plot(fignames{ifig},data,names,alias,units,prfix,years,save);
   end
   
   %--------------------------------------------------------------------------------------------
   % Total Carbon, PFT-Split
   %--------------------------------------------------------------------------------------------
   if ~isempty(splt)
      if any(sum(cell2mat(split)) == 0); continue; end
      
      if any(splt == 'H')
         killpanel = [];
         for i = 1:numel(names)
            prfix{i} = 'H';
            if split{i} == 0;
               killpanel = [killpanel i];
            end
         end
         util_panel_plot(hw_fname{ifig},data,names,alias,units,prfix,years,save,killpanel);
      end

      
      if any(splt == 'C')
         killpanel = [];
         for i = 1:numel(names)
            prfix{i} = 'C';
            if split{i} == 0;
               killpanel = [killpanel i];
            end
         end
         util_panel_plot(co_fname{ifig},data,names,alias,units,prfix,years,save,killpanel);
      end

   end
   
   if plot_c13
      fignames{ifig} = [fignames{ifig} ' delta 13C'];
      for i = 1:numel(names)
          [~, names{i}]  = get_iso_name(names{i});
          alias{i}  = [alias{i} ' \delta ^1^3C'];
          units{i}  = 'permil';
      end

      killpanel = 0;
      util_panel_plot(fignames{ifig}, ...
                data,...
                names,...
                alias,...
                units,...
                prfix,...
                years,...
                save,...
                killpanel);
   end
end

end
